repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_annotation: com.google.code.findbugs:jsr305:jar:3.0.1

  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA
